<?php
function optionsframework_option_name(){
    $themename = wp_get_theme();
    $themename = preg_replace("/\W/","_",strtolower($themename));
    $optionsframework_settings = get_option('optionsframework');
    $optionsframework_settings['id'] = $themename;
    update_option('optionsframework',$optionsframework_settings);
}
function optionsframework_options(){
    $imagepath = get_template_directory_uri().'/inc/theme-options/images/';
    $options = array();
    $options[] = array(
        'name'=>'Site Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Icon',
        'id'=>'site_ico',
        'std'=>'http://cdn.xiaoyou66.com/theme/logo_labe.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Gravatar Server URL',
        'desc'=>'Do not change if unsure',
        'id'=>'gravatar_url',
        'std'=>'cn.gravatar.com/avatar',
        'type'=>'text');
    $options[] = array(
        'name'=>'PJAX',
        'desc'=>'Enable PJAX loading (allows continuous music playback)',
        'id'=>'page_pjax',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sitemap',
        'desc'=>'Whether to Enable Sitemap(generated on post update，Requires /directory write permission)',
        'id'=>'sitemap',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Background Type',
        'desc'=>'Select your preferred Background Typeand modify its options',
        'id'=>'background_mode',
        'std'=>'image',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'color'=>'Solid Color',
            'image'=>'Image','xiaoyou'));
    $options[] = array(
        'name'=>'Background Color',
        'desc'=>'Site-wideBackground ColorControl(Background TypeSelect to Solid Colorto take effect，Select Solid Colormobile Imagewill not be shown)',
        'id'=>'background_index_color',
        'std'=>'#f5f5f5',
        'type'=>'color');
    $options[] = array(
        'name'=>'BackgroundImage',
        'desc'=>'Site-wideBackgroundImageControl(Background TypeSelect to Imageto take effect)',
        'id'=>'background_index_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/background.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Enable mobile backgroundImage',
        'id'=>'openphoneimg',
        'desc'=>'Note:Only when Background Typeto Image is Mobile backgroundImageto display correctly',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Mobile backgroundImage',
        'desc'=>'Enable mobile backgroundImagewill be shown',
        'id'=>'phone_img',
        'std'=>'http://cdn.xiaoyou66.com/theme/phone-packground.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Home Layout',
        'desc'=>'Select Home layout (Left sidebar, No sidebar, Right sidebar). Default: Right.',
        'id'=>"home_side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));
    $options[] = array(
        'name'=>'Post List Layout',
        'desc'=>'Select post list layout. Default: New.',
        'id'=>"list_layout",
        'std'=>"new_layout",
        'type'=>"images",
        'options'=>array(
            'old_layout'=>$imagepath.'old-layout.png',
            'new_layout'=>$imagepath.'new-layout.png'));
    $options[] = array(
        'name'=>'Excerpt Length',
        'desc'=>'Recommended: 110 for CN, 40 for EN. Use with <!--more--> tag.',
        'id'=>'w_num',
        'std'=>'110',
        'type'=>'text');
    $options[] = array(
        'name'=>'Category Page',
        'desc' =>'Whether to Enable Category Page name and descriptionfeature',
        'id'=>'show_head_cat',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Tag Page',
        'desc' =>'Whether to Enable Tag Page name and descriptionfeature',
        'id'=>'show_head_tag',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Local Avatar Upload',
        'desc'=>'Allow users to upload local avatars',
        'id'=>'lo_ava',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Gutenberg',
        'desc'=>'Use Gutenberg Editor',
        'id'=>'use_gutenberg',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sticky Sidebar',
        'desc'=>'Enable sticky sidebar widgets',
        'id'=>'site_sa',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Comment User Agent',
        'desc'=>'Show commenter UA info',
        'id'=>'comment_ua',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Copy Popup',
        'desc'=>'Enable popup after copying content',
        'id'=>'copy_notice',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Page Pseudo-static',
        'desc'=>'Whether to Enable Custom Page Pseudo-staticfeature',
        'id'=>'page_html',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Component Config',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Custom Font Awesome',
        'desc'=>'Custom Font Awesome 4.7font library link，Local if empty',
        'id'=>'fa_url',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Custom jQuery',
        'desc'=>'Custom jQueryLink，Local if empty',
        'id'=>'jq_url',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Additional JS',
        'id'=>'add_script',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Additional CSS',
        'id'=>'add_css',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'featured Image(only for new layout)',
        'desc'=>'Select your preferred Defaultfeatured Image(Random if emptyImage)',
        'id'=>'default_image',
        'type'=>'upload');
    $options[] = array(
        'name'=>'WeChat Show',
        'desc'=>'Whether to Enable WeChat ShowButtonfeature',
        'id'=>'cd_weixin',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'WeChat QR',
        'desc'=>'Upload your WeChat QRImage，Size must be > equal to150px',
        'id'=>'weixin_image',
        'std'=>'',
        'type'=>'upload');
    $options[] = array(
        'name'=>'WeChat Pay QR',
        'desc'=>'Upload your WeChat Pay QRImage，ImageSize must be > 200px',
        'id'=>'wechatpayqr_url',
        'std'=>'http://cdn.xiaoyou66.com/theme/weixin.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Alipay QR',
        'desc'=>'Upload your Alipay QRImage，ImageSize must be > 200px',
        'id'=>'alipayqr_url',
        'std'=>'http://cdn.xiaoyou66.com/theme/alipay.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'SEO Config',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Keywords',
        'desc'=>'Every Keywordsseparated by commas',
        'id'=>'site_keywords',
        'type'=>'text');
    $options[] = array(
        'name'=>'Site Description',
        'id'=>'site_description',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Site Statistics (Exclude SCRIPT tags)',
        'id'=>'script_tongji',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Header Config',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Header Display Mode',
        'id'=>'head_mode',
        'std'=>'pic',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'pic'=>'Image',
            'color'=>'Solid Color'));
    $options[] = array(
        'name'=>'Below are ImageHeader settings',
        'desc'=>'Only Header Display Modeto Imageto take effect。');
    $options[] = array(
        'name'=>'TopImage',
        'id'=>'background_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/header.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'MobileTopImage(optional)',
        'id'=>'background_image_mobi',
        'std'=>'http://cdn.xiaoyou66.com/theme/phone_headr.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'ImageText-1(can be used as TextTitle)',
        'id'=>'background_image_text1',
        'std'=>'Kratos',
        'type'=>'text');
    $options[] = array(
        'name'=>'ImageText-2(can be used as Site Description)',
        'id'=>'background_image_text2',
        'std'=>'A cute anime theme',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mobile Menu Mode',
        'id'=>'mobi_mode',
        'std'=>'side',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'top'=>'Top',
            'side'=>'Side')
    );
    $options[] = array(
        'name'=>'Below are Solid ColorHeaderSettings',
        'desc'=>'Only Header Display Modeto Solid Colorto take effect。');
    $options[] = array(
        'name'=>'Nav Bar Color',
        'desc'=>'Use RGBA format. Default: 22,23,26,.9',
        'id'=>'banner_color',
        'std'=>'22,23,26,.9',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mobile Sidebar Color',
        'desc'=>'Use RGBA format. Default: 42,42,42,.9',
        'id'=>'mobi_color',
        'std'=>'42,42,42,.9',
        'type'=>'text');
    $options[] = array(
        'name'=>'ImageLogo',
        'desc'=>'Height 40px，Max width 200px，Shows text if emptyLogo(Only in Topmode is Solid Colordisplayed correctly)',
        'id'=>'banner_logo',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Footer Config',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Launch Date',
        'desc'=>'Enter your Site Launch Date，FormatMM/DD/YYYY hh:mm:ss',
        'id'=>'createtime',
        'std'=>'03/20/2019 00:00:00',
        'type'=>'text');
    $options[] = array(
        'name'=>'Footer Color',
        'desc'=>'Use RGBA format. Default: 35,40,45,1',
        'id'=>'footer_color',
        'std'=>'35,40,45,1',
        'type'=>'text');
    $options[] = array(
        'name'=>'ICP Info',
        'desc'=>'Enter ICP filing number',
        'id'=>'icp_num',
        'type'=>'text');    
    $options[] = array(
        'name'=>'Police Info',
        'desc'=>'Enter Public Security filing number',
        'id'=>'gov_num',
        'type'=>'text');    
    $options[] = array(
        'name'=>'Police Info Link',
        'desc'=>'Enter Public Security filing link',
        'id'=>'gov_link',
        'type'=>'text');
    $options[] = array(
        'name'=>'Sina Weibo',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_weibo',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Tencent Weibo',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_tweibo',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Twitter',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_twitter',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'FaceBook',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_facebook',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'LinkedIn',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_linkedin',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'GayHub',
        'desc'=>'Must include http:// or https://',
        'id'=>'social_github',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mail',
        'desc'=>'URL must include mailto: ',
        'id'=>'social_mail',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'bilibili',
        'desc'=>'Enter Bilibili UID ',
        'id'=>'social_bilibili',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Post Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Post Page Layout',
        'desc'=>'Select Post layout (Left sidebar, No sidebar, Right sidebar). Default: Right.',
        'id'=>"side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));
    $options[] = array(
        'name'=>'Copyright Notice',
        'desc'=>'Enable CC BY-SA 4.0 notice',
        'id'=>'post_cc',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Share Button',
        'desc'=>'Enable post sharing',
        'id'=>'post_share',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Donate Button',
        'desc'=>'Enable post donation',
        'id'=>'post_like_donate',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Page Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Page Layout',
        'desc'=>'Select Page layout (Left sidebar, No sidebar, Right sidebar). Default: Right.',
        'id'=>"page_side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));    
    $options[] = array(
        'name'=>'Copyright Notice',
        'desc'=>'Enable CC BY-SA 4.0 notice',
        'id'=>'page_cc',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Share Button',
        'desc'=>'Enable page sharing',
        'id'=>'page_share',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Donate Button',
        'desc'=>'Enable page donation',
        'id'=>'page_like_donate',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Slider Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Home Slider',
        'desc'=>'Enable slider',
        'id'=>'kratos_banner',
        'std'=>'0',
        'type'=>'checkbox',);
    $options[] = array(
        'name'=>'Note:',
        'desc'=>'ImageWidth recommended > 750px，All Imageratios must match');
    $options[] = array(
        'name'=>'SliderImage-1',
        'id'=>'kratos_banner1',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Slider Link 1',
        'desc'=>'Link can be empty',
        'id'=>'kratos_banner_url1',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'SliderImage-2',
        'id'=>'kratos_banner2',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 2',
        'desc'=>'Link can be empty',
        'id'=>'kratos_banner_url2',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'SliderImage-3',
        'id'=>'kratos_banner3',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 3',
        'desc'=>'Link can be empty',
        'id'=>'kratos_banner_url3',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'SliderImage-4',
        'id'=>'kratos_banner4',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 4',
        'desc'=>'Link can be empty',
        'id'=>'kratos_banner_url4',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'SliderImage-5',
        'id'=>'kratos_banner5',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 5',
        'desc'=>'Link can be empty',
        'id'=>'kratos_banner_url5',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'SMTP Service',
        'desc'=>'Enable SMTP service',
        'id'=>'mail_smtps',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sender',
        'desc'=>'Sender Name',
        'id'=>'mail_name',
        'std'=>'Moe-dog Services Team',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Server',
        'desc'=>'Please enter SMTP Service Server URL',
        'id'=>'mail_host',
        'std'=>'smtp.office365.com',
        'type'=>'text');
    $options[] = array(
        'name'=>'Server Port',
        'desc'=>'Please enter SMTP Service Server Port',
        'id'=>'mail_port',
        'std'=>'587',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Account',
        'desc'=>'Email Address',
        'id'=>'mail_username',
        'std'=>'no_reply@fczbl.vip',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Password',
        'desc'=>'Please enter Email Password',
        'id'=>'mail_passwd',
        'std'=>'123456789',
        'type'=>'password');
    $options[] = array(
        'name'=>'Enable SMTPAuth',
        'desc'=>'Whether to Enable SMTPAuth',
        'id'=>'mail_smtpauth',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'SMTPSecure Setting',
        'desc'=>'If Enable SMTPAuththen enterssl，If not Enable leave empty；office365 email, please enterSTARTTLS',
        'id'=>'mail_smtpsecure',
        'std'=>'STARTTLS',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Snow',
        'desc'=>'Whether to Enable Site Snowfeature',
        'id'=>'site_snow',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Show on Mobile',
        'desc'=>'Configure Show on Mobile，DefaultYes',
        'id'=>'snow_xb2016_mobile',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Snow Count',
        'desc'=>'Higher value means Snow Countmore ，Default150',
        'id'=>'snow_xb2016_flakecount',
        'std'=>'150',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Size',
        'desc'=>'Base value, higher is larger. Default: 2.',
        'id'=>'snow_xb2016_size',
        'std'=>'2',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Distance',
        'desc'=>'Snow Distancemin from mouse pointer，Snow within this distance will be repelled by mouse，Default100',
        'id'=>'snow_xb2016_mindist',
        'std'=>'100',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Speed',
        'desc'=>'as base value，Higher value means Snow Speedfaster ，Default0.5',
        'id'=>'snow_xb2016_speed',
        'std'=>'0.5',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Sway',
        'desc'=>'Base value, higher is more sway. Default: 1.',
        'id'=>'snow_xb2016_stepsize',
        'std'=>'1',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Color',
        'desc'=>'Use RGB format. Default: 255,255,255',
        'id'=>'snow_xb2016_snowcolor',
        'std'=>'255,255,255',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snow Opacity',
        'desc'=>'Base value (0-1). Default: 0.3.',
        'id'=>'snow_xb2016_opacity',
        'std'=>'0.3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Auth Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Auth Page Background',
        'desc'=>'Uses Bing API by default, or enter link.',
        'id'=>'login_bak',
        'std'=>'http://cdn.xiaoyou66.com/theme/R9K.jpg',
        'type'=>'text');
    $options[] = array(
        'name'=>'Auth pageSite Icon',
        'id'=>'login_logo',
        'std'=>'http://cdn.xiaoyou66.com/theme/logo.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'User Registration Settings');
    $options[] = array(
        'name'=>'Register with Password',
        'desc'=>'Allow registration without email verification',
        'id'=>'mail_reg',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Domain Restriction Mode',
        'desc'=>'Default if no restrictions wanted.',
        'id'=>'dmode',
        'std'=>'black',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'white'=>'Whitelist Mode',
            'black'=>'Blacklist Mode','xiaoyou'));
    $options[] = array(
        'name'=>'Domain Whitelist (one per line)',
        'id'=>'dwhite',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Domain Blacklist (one per line)',
        'id'=>'dblack',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Error Message',
        'desc'=>'Message when domain is blocked',
        'id'=>'derror',
        'std'=>'Registration from this domain is prohibited.',
        'type'=>'text');
    $options[] = array(
        'name'=>'Login Limit Settings',
        'desc'=>'Disabled by default, but recommended.');
    $options[] = array(
        'name'=>'User Login Limit',
        'desc'=>'Enable login limits',
        'id'=>'login_limit',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Login Attempts',
        'desc'=>'Max attempts. Default: 3.',
        'id'=>'allowed_retries',
        'std'=>'3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Initial Lockout Time',
        'desc'=>'In seconds. Default: 1200.',
        'id'=>'lockout_duration',
        'std'=>'1200',
        'type'=>'text');
    $options[] = array(
        'name'=>'Attempts before lockout increase',
        'desc'=>'Default: 3.',
        'id'=>'allowed_lockouts',
        'std'=>'3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Increased Lockout Time',
        'desc'=>'In seconds. Default: 86400.',
        'id'=>'long_duration',
        'std'=>'86400',
        'type'=>'text');
    $options[] = array(
        'name'=>'Clear lockout time',
        'desc'=>'In seconds. Default: 43200.',
        'id'=>'valid_duration',
        'std'=>'43200',
        'type'=>'text');
    $options[] = array(
        'name'=>'Control Cookie Login',
        'desc'=>'Whether to Control Cookie Login',
        'id'=>'cookies',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Email Alert',
        'desc'=>'Whether to Enable Lockout Email Alertfeature(Please below Settingsalert threshold)',
        'id'=>'lockout_notify_m',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Alert Threshold',
        'desc'=>'Default2 times(Enable above Email Alertfeatureto take effect)',
        'id'=>'notify_email_after',
        'std'=>'2',
        'type'=>'text');
    $options[] = array(
        'name'=>'Other Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Enable Music Player',
        'desc'=>'Enables Qplayer',
        'id'=>'openmusicplug',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Show Table of Contents',
        'desc'=>'Shows TOC on post pages',
        'id'=>'opencontent',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Live2D Waifu',
        'desc'=>'Shows Live2D Waifu on site',
        'id'=>'openlive2d',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Subscription',
        'desc'=>'Shows subscription options on profile',
        'id'=>'openpassage',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Show RSS',
        'desc'=>'will be at the bottomShow RSSButton',
        'id'=>'show_rss',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Editor Enhancement',
        'desc'=>'Enables tinymce enhancement',
        'id'=>'open_tinymce',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Code Plugin',
        'desc'=>'Enables Enlighter plugin',
        'id'=>'open_enlighter',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Music Player Default State',
        'desc'=>'Expand player by default',
        'id'=>'open_music',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Post Animation Effect',
        'desc'=>'Enable animations site-wide',
        'id'=>'animal_load',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sidebar Avatar',
        'desc'=>'Shown on mobile sidebar',
        'id'=>'phone_sideer_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/admin_avatar-96x96.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Nickname',
        'desc'=>'Shown on mobile sidebar',
        'id'=>'person_nickname',
        'std'=>'XiaoYou',
        'type'=>'text');
    $options[] = array(
        'name'=>'Avatar Link',
        'desc'=>'Link when avatar is clicked',
        'id'=>'person_link',
        'std'=>'https://xiaoyou66.com/about/',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bio',
        'desc'=>'Shown on mobile sidebar(keep it short)',
        'id'=>'person_sign',
        'std'=>'Anime Tech Otaku',
        'type'=>'text');
    $options[] = array(
        'name'=>'BSiteUID',
        'desc'=>'Show your anime progress',
        'id'=>'bilibili_uid',
        'std'=>'343147393',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bilibili Cookie Data',
        'desc'=>'Show detailed anime progress',
        'id'=>'bilibili_cookie',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Home Category Filter',
        'desc'=>'Filter categories. Format: "-5,-6"',
        'id'=>'filter',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Title on Page Hide',
        'desc'=>'Title shown when tab is hidden',
        'id'=>'title_change',
        'std'=>'404! !!!∑(ﾟДﾟノ)ノ',
        'type'=>'text');
    $options[] = array(
        'name'=>'Title on Page Show',
        'desc'=>'Title shown when tab is active',
        'id'=>'title_back',
        'std'=>'Haha, just kidding! ヾ(ﾟ∀ﾟゞ)',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mouse Click Content',
        'desc'=>'Text shown on click (separate with commas in quotes)',
        'id'=>'click_content',
        'std'=>'"Tech Otaku", "Anime", "Newbie", "Imaginative", "*:ஐ٩(๑´ᵕ`)۶ஐ:* Learning makes me progress", "(๑*◡*๑)", "✧*｡٩(ˊᗜˋ*)و✧*｡" ,"（づ￣3￣）づ╭❤～", "╰( ´・ω・)つ──☆✿✿✿", "Passionate", "(((┏(;￣▽￣)┛Hit and run", "Night owl(,,•﹏•,,)"',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Custom Random Post Backgrounds',
        'desc'=>'Note: Default will be disabled. One per line.',
        'id'=>'random_image',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Custom Random Avatars',
        'desc'=>'Note: Default will be disabled. One per line.',
        'id'=>'random_avatar',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Waifu Dock Position',
        'desc'=>'Waifu Dock Position，e.g. left:0(left 0px), right:30(right 30px)',
        'id'=>'wifuside',
        'std'=>'left:30',
        'type'=>'text');
    $options[] = array(
        'name'=>'Waifu Auto Switch Side',
        'desc'=>'Switch side on post pages',
        'id'=>'wifuchange',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'B-Blog Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Enable B-Blog',
        'desc'=>'Must create a page with B-Blog template',
        'id'=>'bibo_open',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'B-Blog Page URL',
        'desc'=>'Enter your B-Blog URL',
        'id'=>'bibo_pagelink',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Default redirect to B-Blog',
        'desc'=>'Redirect home to B-Blog',
        'id'=>'bibo_gotobibo',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Bilibili Auth Description',
        'desc'=>'Shown as your auth content',
        'id'=>'bibo_auth',
        'std'=>'A poor uploader who will never be famous',
        'type'=>'text');
    $options[] = array(
        'name'=>'Location',
        'desc'=>'Your location. Hidden if empty.',
        'id'=>'bibo_palce',
        'std'=>'From a distant anime world',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bio',
        'desc'=>'Enter your Bio，or other text content',
        'id'=>'bibo_descript',
        'std'=>'Loves tinkering with software and hardwareAnime Tech Otaku',
        'type'=>'text');
    $options[] = array(
        'name'=>'B-Blog Background',
        'desc'=>'Here Settingsyour B-Blog Background',
        'id'=>'bibo_background',
        'std'=>'http://cdn.xiaoyou66.com/theme/3O1R.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Promo Link Text',
        'desc'=>'Enter link text',
        'id'=>'bibo_push',
        'std'=>'Love Box',
        'type'=>'text');
    $options[] = array(
        'name'=>'Promo Link URL',
        'desc'=>'Enter link URL',
        'id'=>'bibo_pushlink',
        'std'=>'https://xiaoyou66.com/%e7%88%b1%e5%bf%83%e7%ae%b1',
        'type'=>'text');
    $options[] = array(
        'name'=>'View More URL',
        'desc'=>'Enter link URL',
        'id'=>'bibo_more',
        'std'=>'https://xiaoyou66.com/about',
        'type'=>'text');
    $options[] = array(
        'name'=>'Notice Content',
        'desc'=>'Shown on notice board. Hidden if empty.',
        'id'=>'bibo_post',
        'std'=>'New features are being tested...',
        'type'=>'text');
    $options[] = array(
        'name'=>'Enable Friend Links',
        'desc'=>'Enable and show friend links',
        'id'=>'bibo_friend',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Hot Posts',
        'desc'=>'Enable and show hot posts',
        'id'=>'bibo_hot',
        'std'=>'1',
        'type'=>'checkbox');
    return $options;
}