<?php
function optionsframework_option_name(){
    $themename = wp_get_theme();
    $themename = preg_replace("/\W/","_",strtolower($themename));
    $optionsframework_settings = get_option('optionsframework');
    $optionsframework_settings['id'] = $themename;
    update_option('optionsframework',$optionsframework_settings);
}
function optionsframework_options(){
    $imagepath = get_template_directory_uri().'/inc/theme-options/images/';
    $options = array();
    $options[] = array(
        'name'=>'Site Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Icon',
        'id'=>'site_ico',
        'std'=>'http://cdn.xiaoyou66.com/theme/logo_labe.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Gravatar Server Address',
        'desc'=>'Do not change if unsure',
        'id'=>'gravatar_url',
        'std'=>'cn.gravatar.com/avatar',
        'type'=>'text');
    $options[] = array(
        'name'=>'PJAX',
        'desc'=>'Enable PJAX loading to allow music to continue playing when switching pages',
        'id'=>'page_pjax',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sitemap',
        'desc'=>'Enable sitemap (generated when updating articles, requires write permission for the root directory)',
        'id'=>'sitemap',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Background Type',
        'desc'=>'Choose your preferred background type and modify its corresponding options',
        'id'=>'background_mode',
        'std'=>'image',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'color'=>'Solid Color',
            'image'=>'Image','xiaoyou'));
    $options[] = array(
        'name'=>'Background Color',
        'desc'=>'Control the site-wide background color (only valid if background type is set to Solid Color; mobile images will not display)',
        'id'=>'background_index_color',
        'std'=>'#f5f5f5',
        'type'=>'color');
    $options[] = array(
        'name'=>'Background Image',
        'desc'=>'Control the site-wide background image (only valid if background type is set to Image)',
        'id'=>'background_index_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/background.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Enable Mobile Background Image',
        'id'=>'openphoneimg',
        'desc'=>'Note: Mobile background image only displays if background type is set to Image',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Mobile Background Image',
        'desc'=>'Only displays if Enable Mobile Background Image is checked',
        'id'=>'phone_img',
        'std'=>'http://cdn.xiaoyou66.com/theme/phone-packground.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Homepage Layout',
        'desc'=>'Choose [Homepage] layout (Left Sidebar, No Sidebar, Right Sidebar), default is Right Sidebar',
        'id'=>"home_side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));
    $options[] = array(
        'name'=>'Article List Layout',
        'desc'=>'Choose your preferred list layout, default is New Layout',
        'id'=>"list_layout",
        'std'=>"new_layout",
        'type'=>"images",
        'options'=>array(
            'old_layout'=>$imagepath.'old-layout.png',
            'new_layout'=>$imagepath.'new-layout.png'));
    $options[] = array(
        'name'=>'Homepage Article Excerpt Length',
        'desc'=>'Recommended: 110 for Chinese, 40 for English, used with the more tag',
        'id'=>'w_num',
        'std'=>'110',
        'type'=>'text');
    $options[] = array(
        'name'=>'Category Page',
        'desc' =>'Enable name and description for category pages',
        'id'=>'show_head_cat',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Tag Page',
        'desc' =>'Enable name and description for tag pages',
        'id'=>'show_head_tag',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Local Avatar Upload',
        'desc'=>'Allow regular users to upload local avatars',
        'id'=>'lo_ava',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Gutenberg',
        'desc'=>'Whether to use Gutenberg editor',
        'id'=>'use_gutenberg',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sticky Sidebar',
        'desc'=>'Enable sticky functionality for sidebar widgets',
        'id'=>'site_sa',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Comment UA',
        'desc'=>'Display commenter UA information in the comment area',
        'id'=>'comment_ua',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Copy Notice',
        'desc'=>'Enable popup notice after copying article content',
        'id'=>'copy_notice',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Page Pseudo-static',
        'desc'=>'Enable custom page pseudo-static functionality',
        'id'=>'page_html',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Component Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Custom Font Awesome',
        'desc'=>'Custom Font Awesome 4.7 library link, leave empty to load from local',
        'id'=>'fa_url',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Custom jQuery',
        'desc'=>'Custom jQuery link, leave empty to load from local',
        'id'=>'jq_url',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Additional JS',
        'id'=>'add_script',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Additional CSS',
        'id'=>'add_css',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Featured Image (New Layout only)',
        'desc'=>'Choose your preferred default featured image (leave empty for random)',
        'id'=>'default_image',
        'type'=>'upload');
    $options[] = array(
        'name'=>'WeChat Display',
        'desc'=>'Enable WeChat display button functionality',
        'id'=>'cd_weixin',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'WeChat QR Code',
        'desc'=>'Upload your WeChat QR code image, size should be at least 150px',
        'id'=>'weixin_image',
        'std'=>'',
        'type'=>'upload');
    $options[] = array(
        'name'=>'WeChat Pay QR Code',
        'desc'=>'Upload your WeChat Pay QR code, size should be at least 200px',
        'id'=>'wechatpayqr_url',
        'std'=>'http://cdn.xiaoyou66.com/theme/weixin.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Alipay QR Code',
        'desc'=>'Upload your Alipay QR code, size should be at least 200px',
        'id'=>'alipayqr_url',
        'std'=>'http://cdn.xiaoyou66.com/theme/alipay.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'SEO Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Keywords',
        'desc'=>'Separate keywords with English commas',
        'id'=>'site_keywords',
        'type'=>'text');
    $options[] = array(
        'name'=>'Site Description',
        'id'=>'site_description',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Site Statistics (Please remove SCRIPT tags)',
        'id'=>'script_tongji',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Header Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Header Display Mode',
        'id'=>'head_mode',
        'std'=>'pic',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'pic'=>'Image',
            'color'=>'Solid Color'));
    $options[] = array(
        'name'=>'Header Settings for Image Mode',
        'desc'=>'Only valid if Header Display Mode is set to Image.');
    $options[] = array(
        'name'=>'Header Image',
        'id'=>'background_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/header.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Mobile Header Image (Optional)',
        'id'=>'background_image_mobi',
        'std'=>'http://cdn.xiaoyou66.com/theme/phone_headr.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Header Text-1 (Title)',
        'id'=>'background_image_text1',
        'std'=>'Kratos',
        'type'=>'text');
    $options[] = array(
        'name'=>'Header Text-2 (Description)',
        'id'=>'background_image_text2',
        'std'=>'A cute anime-style theme',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mobile Menu Display Mode',
        'id'=>'mobi_mode',
        'std'=>'side',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'top'=>'Top',
            'side'=>'Sidebar')
    );
    $options[] = array(
        'name'=>'Header Settings for Solid Color Mode',
        'desc'=>'Only valid if Header Display Mode is set to Solid Color.');
    $options[] = array(
        'name'=>'Nav Bar Color',
        'desc'=>'Please use RGBA format, default 22,23,26,.9',
        'id'=>'banner_color',
        'std'=>'22,23,26,.9',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mobile Sidebar Menu Color',
        'desc'=>'Please use RGBA format, default 42,42,42,.9',
        'id'=>'mobi_color',
        'std'=>'42,42,42,.9',
        'type'=>'text');
    $options[] = array(
        'name'=>'Image Logo',
        'desc'=>'Height 40px, Max width 200px. If not set, text logo will display (only for Solid Color mode)',
        'id'=>'banner_logo',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Footer Configuration',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Creation Time',
        'desc'=>'Enter site creation time, format MM/DD/YYYY hh:mm:ss',
        'id'=>'createtime',
        'std'=>'03/20/2019 00:00:00',
        'type'=>'text');
    $options[] = array(
        'name'=>'Footer Color',
        'desc'=>'Please use RGBA format, default 35,40,45,1',
        'id'=>'footer_color',
        'std'=>'35,40,45,1',
        'type'=>'text');
    $options[] = array(
        'name'=>'MIIT Filing Information',
        'desc'=>'Enter your MIIT filing number',
        'id'=>'icp_num',
        'type'=>'text');    
    $options[] = array(
        'name'=>'PSB Filing Information',
        'desc'=>'Enter your Public Security Bureau filing number',
        'id'=>'gov_num',
        'type'=>'text');    
    $options[] = array(
        'name'=>'PSB Filing Link',
        'desc'=>'Enter the link to your Public Security Bureau filing',
        'id'=>'gov_link',
        'type'=>'text');
    $options[] = array(
        'name'=>'Sina Weibo',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_weibo',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Tencent Weibo',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_tweibo',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Twitter',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_twitter',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'FaceBook',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_facebook',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'LinkedIn',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_linkedin',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'GayHub',
        'desc'=>'Link must start with http:// or https:// ',
        'id'=>'social_github',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mail',
        'desc'=>'Link must start with mailto: ',
        'id'=>'social_mail',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bilibili',
        'desc'=>'Enter Bilibili UID ',
        'id'=>'social_bilibili',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Article Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Article Page Layout',
        'desc'=>'Choose [Article] page layout (Left Sidebar, No Sidebar, Right Sidebar), default is Right Sidebar',
        'id'=>"side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));
    $options[] = array(
        'name'=>'Copyright Declaration',
        'desc'=>'Enable CC BY-SA 4.0 statement',
        'id'=>'post_cc',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Share Button',
        'desc'=>'Enable article sharing functionality',
        'id'=>'post_share',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Donate Button',
        'desc'=>'Enable article donation functionality',
        'id'=>'post_like_donate',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Page Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Page Layout',
        'desc'=>'Choose [Page] layout (Left Sidebar, No Sidebar, Right Sidebar), default is Right Sidebar',
        'id'=>"page_side_bar",
        'std'=>"right_side",
        'type'=>"images",
        'options'=>array(
            'left_side'=>$imagepath.'col-left.png',
            'center'=>$imagepath.'col.png',
            'right_side'=>$imagepath.'col-right.png'));    
    $options[] = array(
        'name'=>'Copyright Declaration',
        'desc'=>'Enable CC BY-SA 4.0 statement',
        'id'=>'page_cc',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Share Button',
        'desc'=>'Enable page sharing functionality',
        'id'=>'page_share',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Donate Button',
        'desc'=>'Enable page donation functionality',
        'id'=>'page_like_donate',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Carousel Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Homepage Carousel',
        'desc'=>'Enable carousel functionality',
        'id'=>'kratos_banner',
        'std'=>'0',
        'type'=>'checkbox',);
    $options[] = array(
        'name'=>'Note:',
        'desc'=>'Image width suggested > 750px, proportions must be consistent');
    $options[] = array(
        'name'=>'Carousel Image-1',
        'id'=>'kratos_banner1',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Carousel Link-1',
        'desc'=>'Link can be left empty',
        'id'=>'kratos_banner_url1',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Carousel Image-2',
        'id'=>'kratos_banner2',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 2',
        'desc'=>'Link can be left empty',
        'id'=>'kratos_banner_url2',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Carousel Image-3',
        'id'=>'kratos_banner3',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 3',
        'desc'=>'Link can be left empty',
        'id'=>'kratos_banner_url3',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Carousel Image-4',
        'id'=>'kratos_banner4',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 4',
        'desc'=>'Link can be left empty',
        'id'=>'kratos_banner_url4',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Carousel Image-5',
        'id'=>'kratos_banner5',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Link 5',
        'desc'=>'Link can be left empty',
        'id'=>'kratos_banner_url5',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'SMTP Service',
        'desc'=>'Enable SMTP mail service',
        'id'=>'mail_smtps',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sender',
        'desc'=>'Enter sender name',
        'id'=>'mail_name',
        'std'=>'Moe-dog Services Team',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mail Server',
        'desc'=>'Enter SMTP server address',
        'id'=>'mail_host',
        'std'=>'smtp.office365.com',
        'type'=>'text');
    $options[] = array(
        'name'=>'Server Port',
        'desc'=>'Enter SMTP server port',
        'id'=>'mail_port',
        'std'=>'587',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Account',
        'desc'=>'Enter email account',
        'id'=>'mail_username',
        'std'=>'no_reply@fczbl.vip',
        'type'=>'text');
    $options[] = array(
        'name'=>'Email Password',
        'desc'=>'Enter email password',
        'id'=>'mail_passwd',
        'std'=>'123456789',
        'type'=>'password');
    $options[] = array(
        'name'=>'Enable SMTPAuth Service',
        'desc'=>'Enable SMTPAuth service',
        'id'=>'mail_smtpauth',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'SMTPSecure Setting',
        'desc'=>'Fill ssl if SMTPAuth is enabled, else leave empty; use STARTTLS for Office365',
        'id'=>'mail_smtpsecure',
        'std'=>'STARTTLS',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Site Snowflakes',
        'desc'=>'Enable site-wide snowflake effect',
        'id'=>'site_snow',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Display on Mobile',
        'desc'=>'Whether to display on mobile, default Yes',
        'id'=>'snow_xb2016_mobile',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Snowflake Count',
        'desc'=>'Larger value = more snowflakes, default 150',
        'id'=>'snow_xb2016_flakecount',
        'std'=>'150',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Size',
        'desc'=>'Base value, larger = larger flakes, default 2',
        'id'=>'snow_xb2016_size',
        'std'=>'2',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Distance',
        'desc'=>'Min distance from mouse; snowflakes within this range are repelled, default 100',
        'id'=>'snow_xb2016_mindist',
        'std'=>'100',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Speed',
        'desc'=>'Base value, larger = faster speed, default 0.5',
        'id'=>'snow_xb2016_speed',
        'std'=>'0.5',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Drift',
        'desc'=>'Base value, larger = more horizontal drift, 0 is vertical, default 1',
        'id'=>'snow_xb2016_stepsize',
        'std'=>'1',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Color',
        'desc'=>'Use RGB format, default 255,255,255',
        'id'=>'snow_xb2016_snowcolor',
        'std'=>'255,255,255',
        'type'=>'text');
    $options[] = array(
        'name'=>'Snowflake Opacity',
        'desc'=>'Base value, range 0~1, 1 is opaque, default 0.3',
        'id'=>'snow_xb2016_opacity',
        'std'=>'0.3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Registration & Login Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Registration/Login Page Background',
        'desc'=>'Uses Bing API by default, so enter link manually here...',
        'id'=>'login_bak',
        'std'=>'http://cdn.xiaoyou66.com/theme/R9K.jpg',
        'type'=>'text');
    $options[] = array(
        'name'=>'Registration/Login Page Icon',
        'id'=>'login_logo',
        'std'=>'http://cdn.xiaoyou66.com/theme/logo.png',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Settings for User Registration');
    $options[] = array(
        'name'=>'Register with Password',
        'desc'=>'Allow users to set password during registration (skip email verification)',
        'id'=>'mail_reg',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Domain Restriction Mode',
        'desc'=>'If no email restriction needed, keep this section as default.',
        'id'=>'dmode',
        'std'=>'black',
        'type'=>'select',
        'class'=>'mini',
        'options'=>array(
            'white'=>'Whitelist Mode',
            'black'=>'Blacklist Mode','xiaoyou'));
    $options[] = array(
        'name'=>'Domain Whitelist (one per line)',
        'id'=>'dwhite',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Domain Blacklist (one per line)',
        'id'=>'dblack',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Error Message',
        'desc'=>'Message shown when user domain is blocked',
        'id'=>'derror',
        'std'=>'This domain is prohibited for registration. Please use another email.',
        'type'=>'text');
    $options[] = array(
        'name'=>'Settings for Login Restriction',
        'desc'=>'Disabled by default, but manual activation is recommended');
    $options[] = array(
        'name'=>'User Login Restriction',
        'desc'=>'Enable login restriction (required for settings below)',
        'id'=>'login_limit',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Login Retries',
        'desc'=>'Allowed password attempts, default 3',
        'id'=>'allowed_retries',
        'std'=>'3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Initial Lockout Duration',
        'desc'=>'In seconds, min 60, default 1200 (20m)',
        'id'=>'lockout_duration',
        'std'=>'1200',
        'type'=>'text');
    $options[] = array(
        'name'=>'Lockouts before increasing duration',
        'desc'=>'Default 3 times',
        'id'=>'allowed_lockouts',
        'std'=>'3',
        'type'=>'text');
    $options[] = array(
        'name'=>'Increased Lockout Duration',
        'desc'=>'In seconds, min 3600, default 86400 (24h)',
        'id'=>'long_duration',
        'std'=>'86400',
        'type'=>'text');
    $options[] = array(
        'name'=>'Auto-clear Locked IP Time',
        'desc'=>'In seconds, default 43200 (12h)',
        'id'=>'valid_duration',
        'std'=>'43200',
        'type'=>'text');
    $options[] = array(
        'name'=>'Control Cookie Login',
        'desc'=>'Whether to control cookie login',
        'id'=>'cookies',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Email Notification',
        'desc'=>'Enable email notification for lockouts',
        'id'=>'lockout_notify_m',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Lockout Notification Threshold',
        'desc'=>'Default 2 times (requires email notification enabled)',
        'id'=>'notify_email_after',
        'std'=>'2',
        'type'=>'text');
    $options[] = array(
        'name'=>'Other Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Enable Music Player Plugin',
        'desc'=>'Will enable QPlayer music player',
        'id'=>'openmusicplug',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Display Article TOC Module',
        'desc'=>'Will display TOC on article pages',
        'id'=>'opencontent',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Live2D Model',
        'desc'=>'Will display Live2D model on your site',
        'id'=>'openlive2d',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Article Subscription',
        'desc'=>'Enable subscription options on user profile page',
        'id'=>'openpassage',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Display RSS Subscription',
        'desc'=>'Will display RSS subscription button at the bottom',
        'id'=>'show_rss',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Editor Enhancement',
        'desc'=>'Enable TinyMCE plugin for more editor features',
        'id'=>'open_tinymce',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Code Plugin',
        'desc'=>'Enable Enlighter plugin for better code insertion experience',
        'id'=>'open_enlighter',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Music Player Default State',
        'desc'=>'Check to expand music player by default',
        'id'=>'open_music',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Article Animation Loading Effect',
        'desc'=>'Check to enable site-wide animation loading effect',
        'id'=>'animal_load',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Sidebar Personal Avatar',
        'desc'=>'Will be shown in mobile sidebar',
        'id'=>'phone_sideer_image',
        'std'=>'http://cdn.xiaoyou66.com/theme/admin_avatar-96x96.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Nickname',
        'desc'=>'Will be shown in mobile sidebar',
        'id'=>'person_nickname',
        'std'=>'XiaoYou',
        'type'=>'text');
    $options[] = array(
        'name'=>'Avatar Jump Link',
        'desc'=>'Link to jump to when avatar is clicked',
        'id'=>'person_link',
        'std'=>'https://xiaoyou66.com/about/',
        'type'=>'text');
    $options[] = array(
        'name'=>'Personal Signature',
        'desc'=>'Shown in mobile sidebar (keep it short)',
        'id'=>'person_sign',
        'std'=>'Anime Tech Geek',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bilibili UID',
        'desc'=>'Used for anime tracking display',
        'id'=>'bilibili_uid',
        'std'=>'343147393',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bilibili Cookie Data',
        'desc'=>'Used for detailed anime tracking info',
        'id'=>'bilibili_cookie',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name' => 'AniList Username',
        'desc' => 'Used for international anime tracking display (overrides Bilibili)',
        'id' => 'anilist_username',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name'=>'Homepage Directory Filtering',
        'desc'=>'Filter directory content. Format: "-5,-6" (minus sign + ID, comma separated)',
        'id'=>'filter',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Title when Tab is Inactive',
        'desc'=>'Content shown when tab is inactive (leave empty to disable)',
        'id'=>'title_change',
        'std'=>'404! !!!∑(ﾟДﾟノ)ノ',
        'type'=>'text');
    $options[] = array(
        'name'=>'Title when Tab is Re-activated',
        'desc'=>'Content shown when tab is re-activated (leave empty to disable)',
        'id'=>'title_back',
        'std'=>'Haha, just kidding! ヾ(ﾟ∀ﾟゞ)',
        'type'=>'text');
    $options[] = array(
        'name'=>'Mouse Click Content',
        'desc'=>'Text shown when clicking on any page (Must be double-quoted and comma separated)',
        'id'=>'click_content',
        'std'=>'"Tech Geek", "Anime", "Novice", "Imaginative", "*:ஐ٩(๑´ᵕ`)۶ஐ:* Learning makes me progress", "(๑*◡*๑)", "✧*｡٩(ˊᗜˋ*)و✧*｡" ,"(づ￣3￣)づ╭❤～", "╰( ´・ω・)つ──☆✿✿✿", "Passionate", "(((┏(;￣▽￣)┛Run after pretending", "Addicted to staying up late (,,•﹏•,,)"',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Custom Random Article Background Images',
        'desc'=>'Note: Default will be disabled, only these will show (one per line). Full link required.',
        'id'=>'random_image',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Custom Random Avatars',
        'desc'=>'Note: Default will be disabled, only these will show (one per line). Full link required.',
        'id'=>'random_avatar',
        'std'=>'',
        'type'=>'textarea');
    $options[] = array(
        'name'=>'Live2D Alignment',
        'desc'=>'Alignment, e.g., left:0 (left 0px), right:30 (right 30px)',
        'id'=>'wifuside',
        'std'=>'left:30',
        'type'=>'text');
    $options[] = array(
        'name'=>'Article Page Live2D Side Swap',
        'desc'=>'Model automatically moves to the opposite side on article pages',
        'id'=>'wifuchange',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Social Dynamics Settings',
        'type'=>'heading');
    $options[] = array(
        'name'=>'Enable Social Dynamics Functionality',
        'desc'=>'Note: You must create a page using the Bilibili Dynamics template for this to work',
        'id'=>'bibo_open',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name' => 'Mastodon Instance URL',
        'desc' => 'e.g., mastodon.social (overrides Bilibili Dynamics)',
        'id' => 'mastodon_instance',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => 'Mastodon User ID',
        'desc' => 'Numeric ID of your Mastodon account',
        'id' => 'mastodon_user_id',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => 'YouTube API Key',
        'desc' => 'Required for YouTube Dynamics',
        'id' => 'youtube_api_key',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => 'YouTube Channel ID',
        'desc' => 'Your YouTube Channel ID',
        'id' => 'youtube_channel_id',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => 'Bluesky Handle',
        'desc' => 'e.g., user.bsky.social (overrides Bilibili Dynamics)',
        'id' => 'bluesky_handle',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name'=>'Dynamics Page URL',
        'desc'=>'Link to your Social Dynamics page (supports Bilibili and Mastodon)',
        'id'=>'bibo_pagelink',
        'std'=>'',
        'type'=>'text');
    $options[] = array(
        'name'=>'Auto-redirect to Bilibili Dynamics (Requires Page URL)',
        'desc'=>'When enabled, visiting homepage will show Bilibili Dynamics interface',
        'id'=>'bibo_gotobibo',
        'std'=>'0',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Bilibili Personal Authentication Intro',
        'desc'=>'Your personal authentication content will be shown here',
        'id'=>'bibo_auth',
        'std'=>'A poor UP master who will never be famous',
        'type'=>'text');
    $options[] = array(
        'name'=>'Location',
        'desc'=>'Your location, hidden if empty',
        'id'=>'bibo_palce',
        'std'=>'From a distant anime world',
        'type'=>'text');
    $options[] = array(
        'name'=>'Personal Intro',
        'desc'=>'Your personal introduction or other text',
        'id'=>'bibo_descript',
        'std'=>'An anime tech geek who loves tinkering with software and hardware',
        'type'=>'text');
    $options[] = array(
        'name'=>'Bilibili Dynamics Background',
        'desc'=>'Set your Bilibili Dynamics background here',
        'id'=>'bibo_background',
        'std'=>'http://cdn.xiaoyou66.com/theme/3O1R.jpg',
        'type'=>'upload');
    $options[] = array(
        'name'=>'Promotion Link Text',
        'desc'=>'Any text, clicks will redirect',
        'id'=>'bibo_push',
        'std'=>'Love Box',
        'type'=>'text');
    $options[] = array(
        'name'=>'Promotion Link URL',
        'desc'=>'Redirect URL',
        'id'=>'bibo_pushlink',
        'std'=>'https://xiaoyou66.com/%e7%88%b1%e5%bf%83%e7%ae%b1',
        'type'=>'text');
    $options[] = array(
        'name'=>'View More Redirect URL',
        'desc'=>'Redirect URL',
        'id'=>'bibo_more',
        'std'=>'https://xiaoyou66.com/about',
        'type'=>'text');
    $options[] = array(
        'name'=>'Announcement Content',
        'desc'=>'Content shown on the announcement board (hidden if empty)',
        'id'=>'bibo_post',
        'std'=>'New features are currently in testing...',
        'type'=>'text');
    $options[] = array(
        'name'=>'Enable Friend Links',
        'desc'=>'Enable to show theme-added friend links',
        'id'=>'bibo_friend',
        'std'=>'1',
        'type'=>'checkbox');
    $options[] = array(
        'name'=>'Enable Hot Articles',
        'desc'=>'Enable to show hot articles',
        'id'=>'bibo_hot',
        'std'=>'1',
        'type'=>'checkbox');
    return $options;
}